apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"

spec:
  ingressClassName: nginx             
  rules:
    - host: python-web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-canary-svc
                port:
                  number: 80

