apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-base-ingress
spec:
  ingressClassName: nginx            
  rules:
    - host: python-web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-stable-svc
                port:
                  number: 80

